---
- name: Install docker by get.docker.com
  shell: curl https://get.docker.com | bash -s
  when:
    - install_by == "curl"

- name: Install docker by pip package
  pip:
    name: docker-py
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
    - install_by == "pip"

- name: Add Docker GPG apt Key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  when:
    - ansible_os_family == "Debian"
    - install_by == "repo"

- name: Add Docker Repository (deb)
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  when:
    - ansible_os_family == "Debian"
    - install_by == "external-repo"

- name: Add Docker Repository (deb)
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  when:
    - ansible_os_family == "Debian"
    - install_by == "external-repo"

- name: Add Docker repository.
  get_url:
    url: "https://download.docker.com/linux/{{ 'centos' if ansible_distribution == 'AlmaLinux' else 'centos' }}/docker-ce.repo"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_os_family == "RedHat"
    - install_by == "external-repo"

- name: Install docker
  package:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when:
    - install_by == "repo"
