---
- name: Install required python3  for centos 7
  yum:
    name:
    - python3
    - pip3
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == 7
    - install_by == "pip"

- name: Install required pip3
  apt:
    name:
    - python3-pip
    state: present
  when:
      - install_by == "pip"

- name: Install Docker
  include_tasks: _install_docker_by.yml

- name: Configuring logrotate
  template:
    src: docker.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: "0644"

- name: Install Docker-Compose
  include_tasks: _install_compose.yml